### ISSUE TITLE
Does this only list files?

### ISSUE THREAD

**Issue by johnjelinek** [gruntwork-io/s3ls#3]
The description leads me to believe it downloads files from an s3 bucket, but usage in the Readme only mentions `s3ls` and not `s3dl`.

**Comment by johnjelinek** [comment]
Ah, I see downloading was removed in `v0.0.2`. 😭

**Comment by josh-padnick** [comment]
I must admit I never expected any public activity on this de minimum piece of open source! But to confirm what you already found yourself, this only does listing for now.

To download files, the easiest thing to do is use the AWS CLI with a command like `aws s3 cp s3://path/to/file /local/path

**Comment by johnjelinek** [comment]
I can't do AWS CLI from a Lambda function with ease. v0.1.0 is working well
for me.

**Comment by josh-padnick** [comment]
Ah, got it! Thanks also for sharing your use case. Makes me happy I published this as open source.
